# arxivの学問領域の指定
subject: 'cat:cs.SD'

# 検索キーワード
keywords:
        sound: 1
        audio: 2
        optimization: 3
        minimization: 3
        declipping: 3
        inpainting: 3
        norm: 2
        atomic norm: 3
        convex: 2
        sparse: 3
# 通知の閾値
score_threshold: 1
